services:
  # api:
  # build:
  #   dockerfile: Dockerfile
  #   context: .
  #   # Only will build development stage from our dockerfile
  #   target: development
  # env_file:
  #   - .env
  # # Run a command against the development stage of the image
  # environment:
  #   DATABASE_URL: postgresql://postgres:postgres@host.docker.internal.for.windows:5432/sbdb
  # command: npm run start:dev
  # ports:
  #   - 3333:3333
  # depends_on:
  #   - redis
  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sbdb
    ports:
      - '5432:5432'

volumes:
  redis:
    driver: local
  postgres:
